apiVersion: v1
kind: Service
metadata:
  name: mjpeg
spec:
  ports:
    - port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
    name: mjpeg
subsets:
  - addresses:
      - ip: 10.5.0.1
    ports:
      - port: 8080
